In [1]:
from Signal_generator.generate_signal import generate_X_matrix
from Algorithmes.beamforming import beamforming_method
from Signal_generator.generate_signal import generate_A_matrix
from Signal_generator.generate_signal import generate_noise
from Signal_generator.generate_signal import generate_R_hat
from Signal_generator.generate_signal import generate_R_hat_with_phase
from Algorithmes.music import music_method
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split 
import numpy as np
import torch


nbSources = 2 # Nombre de sources
nbSensors = 10 # Nombre de capteurs
nbTimePoints = 100 # Nombre de points temporels
signal_noise_ratio = 3 # Rapport signal sur bruit en décibels. Si 'False', cela revient à une absence totale de bruit.
L = 10
T = 100
correlation_List = [0.4] # Liste des corrélations. Il y a une corrélation nécéssaire pour chaque paire distincte de sources différentes: 0 pour 1 source, 1 pour 2 sources, 3 pour 3 sources, 6 pour 4 sources etc...
# Ordre de remplisage de la correlation_List: de gauche à droite et ligne par ligne, moitié haut-droite de la matrice uniquement, puis symétrie de ces valeurs pour la moitié bas-gauche.


In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

phi_max = 90  # Définition de phi_max
rho = 1  # Résolution de la grille
G = np.arange(-phi_max, phi_max + rho, rho)  # Création de la grille

def angles_to_binary_vector(thetaList, G):
    """
    Convertit une liste d'angles en un vecteur binaire représentant la présence/absence d'angles dans la grille G.
    
    Args:
    - thetaList: Liste des angles d'arrivée pour un échantillon.
    - G: Grille des angles possibles.
    
    Returns:
    - Vecteur binaire des labels Z.
    """
    Z = np.zeros(len(G), dtype=int)
    for theta in thetaList:
        index = np.searchsorted(G, theta)  # Trouver l'indice de l'angle dans la grille
        if 0 <= index < len(G):  # S'assurer que l'indice est dans la plage valide
            Z[index] = 1
    return Z

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

# Paramètres pour la simulation
num_samples = 16290  # Nombre d'échantillons à générer
L = 10  # Nombre de capteurs
T = 100  # Nombre de points temporels
phi_max = 90  # φmax
rho = 1  # Résolution

# Grille des angles
G = np.arange(-phi_max, phi_max + rho, rho)

# Initialisation des tableaux pour les données
all_R_hat_with_phase = np.zeros((num_samples, L, L, 3))
all_Z = np.zeros((num_samples, len(G)))

for i in range(num_samples):
    # Générer les angles d'arrivée et la matrice X comme décrit précédemment
    thetaList = [np.random.uniform(-90, 90) for _ in range(2)]  # Exemple de génération d'angles
    varList = [np.random.uniform(0, 1000000000000) for _ in range(nbSources)]
    X = generate_X_matrix(nbSources, L, T, thetaList, varList, correlation_List, signal_noise_ratio)  # Votre fonction pour générer X, ajoutez les paramètres nécessaires
    
    # Calculer R_hat étendue avec phase
    R_hat_with_phase = generate_R_hat_with_phase(X)
    all_R_hat_with_phase[i] = R_hat_with_phase
    
    # Calculer les labels Z pour les angles générés
    all_Z[i] = angles_to_binary_vector(thetaList, G)

# Division des données en ensembles d'entraînement et de test
X_train, X_test, Z_train, Z_test = train_test_split(all_R_hat_with_phase, all_Z, test_size=0.2, random_state=42)


[[2.11630431e+11 1.70271681e+11]
 [1.70271681e+11 8.56222718e+11]]
[[7.16847048e+11 2.65391635e+11]
 [2.65391635e+11 6.14084277e+11]]
[[2.25202962e+11 1.01984120e+11]
 [1.01984120e+11 2.88649644e+11]]
[[6.31859085e+11 1.67692968e+11]
 [1.67692968e+11 2.78156675e+11]]
[[1.31957504e+11 6.06700494e+10]
 [6.06700494e+10 1.74339029e+11]]
[[5.16925306e+11 1.55271817e+11]
 [1.55271817e+11 2.91499287e+11]]
[[9.99563874e+11 2.87002449e+11]
 [2.87002449e+11 5.15039658e+11]]
[[6.85986358e+11 3.23117739e+11]
 [3.23117739e+11 9.51231319e+11]]
[[6.78279417e+11 1.71295551e+11]
 [1.71295551e+11 2.70373142e+11]]
[[9.36091660e+11 1.83488624e+11]
 [1.83488624e+11 2.24791522e+11]]
[[5.61701240e+11 2.81370297e+11]
 [2.81370297e+11 8.80909175e+11]]
[[5.49718200e+11 9.30929414e+10]
 [9.30929414e+10 9.85311171e+10]]
[[1.23524201e+11 7.35794084e+10]
 [7.35794084e+10 2.73930599e+11]]
[[3.97254704e+11 2.51760486e+11]
 [2.51760486e+11 9.97208810e+11]]
[[8.53068390e+11 3.60948779e+10]
 [3.60948779e+10 9.54525030e+

[[6.29089455e+11 6.06077575e+10]
 [6.06077575e+10 3.64942164e+10]]
[[3.53114863e+11 2.05511563e+11]
 [2.05511563e+11 7.47543628e+11]]
[[4.67315155e+11 6.44897775e+10]
 [6.44897775e+10 5.56226799e+10]]
[[5.99060428e+11 2.59969094e+11]
 [2.59969094e+11 7.05103431e+11]]
[[3.30630002e+11 2.10356425e+11]
 [2.10356425e+11 8.36467983e+11]]
[[2.64074233e+11 1.04072953e+11]
 [1.04072953e+11 2.56347890e+11]]
[[8.35937761e+11 3.63293288e+11]
 [3.63293288e+11 9.86781100e+11]]
[[7.39016872e+11 2.37080092e+11]
 [2.37080092e+11 4.75352562e+11]]
[[3.10065192e+11 7.25585625e+10]
 [7.25585625e+10 1.06121735e+11]]
[[8.21196727e+10 1.09854123e+11]
 [1.09854123e+11 9.18471168e+11]]
[[9.21751965e+11 2.19612179e+11]
 [2.19612179e+11 3.27023367e+11]]
[[1.30775617e+11 1.10977793e+11]
 [1.10977793e+11 5.88606977e+11]]
[[5.34662791e+11 2.38808984e+11]
 [2.38808984e+11 6.66655362e+11]]
[[8.44535053e+11 3.49414448e+11]
 [3.49414448e+11 9.03533076e+11]]
[[3.13373432e+10 6.64925325e+10]
 [6.64925325e+10 8.81786797e+

KeyboardInterrupt: 

In [ ]:
X_train = torch.from_numpy(X_train).to(dtype=torch.float32)
X_test = torch.from_numpy(X_test).to(dtype=torch.float32)
Z_train = torch.from_numpy(Z_train).to(dtype=torch.float32)
Z_test = torch.from_numpy(Z_test).to(dtype=torch.float32)

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np

class DOADataset(Dataset):
    def __init__(self, covariance_matrices, doa_labels):
        """
        Initialisation du Dataset DOA.

        Args:
        - covariance_matrices (np.ndarray): Matrices de covariance étendues avec la phase.
          Forme attendue: (nb_samples, nbSensors, nbSensors, 3) pour les parties réelle, imaginaire, et la phase.
        - doa_labels (np.ndarray): Labels DOA sous forme de vecteurs binaires.
          Forme attendue: (nb_samples, nb_labels), où nb_labels est le nombre de points dans la grille DOA.
        """
        self.covariance_matrices = covariance_matrices
        self.doa_labels = doa_labels

    def __len__(self):
        return len(self.covariance_matrices)

    def __getitem__(self, idx):
      cov_matrix = self.covariance_matrices[idx]
      angle = self.doa_labels[idx]

      # Vérification si cov_matrix est déjà un ndarray, sinon le convertir
      if not isinstance(cov_matrix, np.ndarray):
          cov_matrix = cov_matrix.numpy()  # Convertir en tableau NumPy si ce n'est pas déjà fait
    
      cov_matrix = torch.from_numpy(cov_matrix).float()
      angle = torch.tensor(angle).float()

      return cov_matrix, angle


# Exemple d'utilisation (remplacez R_hat_train/test et angles_train/test par vos données réelles)
train_dataset = DOADataset(X_train, Z_train)
test_dataset = DOADataset(X_test, Z_test)

# Création des DataLoaders pour l'entraînement et le test
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=64, shuffle=False)



In [27]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

# Note: we don't recommend using the "mps" device for this notebook.

print(f"Using {device} device")

Using cpu device


In [149]:
import torch
import torch.nn as nn

class DOACNN(nn.Module):
    def __init__(self, num_channels=10, num_classes=256):
        super(DOACNN, self).__init__()

        # Couches convolutionnelles 2D
        self.conv1 = nn.Conv2d(in_channels=num_channels, out_channels=256, kernel_size=3, stride=2)
        self.conv4 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=2, stride=1)
        self.conv7 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=2, stride=1)
        self.conv10 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=2, stride=1)

        # Normalisation de taille 256
        self.norm2 = nn.BatchNorm2d(256)
        self.norm5 = nn.BatchNorm2d(256)
        self.norm8 = nn.BatchNorm2d(256)
        self.norm11 = nn.BatchNorm2d(256)

        self.relu3 =  nn.ReLU()
        self.relu6 =  nn.ReLU()
        self.relu9 =  nn.ReLU()
        self.relu12 =  nn.ReLU()
        self.relu15 =  nn.ReLU()
        self.relu18 =  nn.ReLU()
        self.relu21 =  nn.ReLU()

        # Couches Dropout
        self.dropout16 = nn.Dropout(0.2)
        self.dropout19 = nn.Dropout(0.2)
        self.dropout22 = nn.Dropout(0.2)

        # Couche d'aplatissement
        self.flatten13 = nn.Flatten()

        # Couches entièrement connectées (FC)
        self.fc14 = nn.Linear(in_features=256 * 7 * 7, out_features=4096)
        self.fc17 = nn.Linear(in_features=4096, out_features=2048)
        self.fc20 = nn.Linear(in_features=2048, out_features=1024)
        self.fc23 = nn.Linear(in_features=1024, out_features=num_classes)

        # Couche de sortie Sigmoid
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.conv1(x)
        x = self.norm2(x)
        x = self.relu3(x)
        x = self.conv4(x)
        x = self.norm5(x)
        x = self.relu6(x)
        x = self.conv7(x)
        x = self.norm8(x)
        x = self.relu9(x)
        x = self.conv10(x)
        x = self.norm11(x)
        x = self.relu12(x)
        x = self.flatten13(x)
        x = self.fc14(x)
        x = self.relu15(x)
        x = self.dropout16(x)
        x = self.fc17(x)
        x = self.relu18(x)
        x = self.dropout19(x)
        x = self.fc20(x)
        x = self.relu21(x)
        x = self.dropout22(x)
        x = self.fc22(x)
        x = self.sigmoid(x)

        return x

# Création d'une instance du modèle
model = DOACNN()
print(model)

DOACNN(
  (conv1): Conv2d(10, 256, kernel_size=(3, 3), stride=(2, 2))
  (conv4): Conv2d(256, 256, kernel_size=(2, 2), stride=(1, 1))
  (conv7): Conv2d(256, 256, kernel_size=(2, 2), stride=(1, 1))
  (conv10): Conv2d(256, 256, kernel_size=(2, 2), stride=(1, 1))
  (norm2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (norm5): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (norm8): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (norm11): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu3): ReLU()
  (relu6): ReLU()
  (relu9): ReLU()
  (relu12): ReLU()
  (relu15): ReLU()
  (relu18): ReLU()
  (relu21): ReLU()
  (dropout16): Dropout(p=0.2, inplace=False)
  (dropout19): Dropout(p=0.2, inplace=False)
  (dropout22): Dropout(p=0.2, inplace=False)
  (flatten13): Flatten(start_dim=1, end_dim=-1)
  (fc14): Linear(in_features=12544, out_features=4096, bia

In [150]:
import torch.optim as optim

learning_rate = 0.001
num_epochs = 10

# Définir la fonction de perte et l'optimiseur
criterion = nn.CrossEntropyLoss()  # Utilisation de la perte d'entropie croisée pour une classification multi-classe
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [151]:
# Boucle d'entraînement
for epoch in range(num_epochs):
    model.train()  # Mettre le modèle en mode d'entraînement

    running_loss = 0.0
    for inputs, labels in train_dataloader:  # train_dataloader est votre DataLoader d'entraînement
        optimizer.zero_grad()  # Réinitialiser les gradients

        # Forward pass
        outputs = model(inputs)

        # Calcul de la perte
        loss = criterion(outputs, labels)

        # Backpropagation et mise à jour des poids
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    # Afficher la perte moyenne pour chaque époque
    print(f'Epoch {epoch + 1}/{num_epochs}, Loss: {running_loss / len(train_dataloader)}')

print('Entraînement terminé!')

C:\Users\natha\AppData\Local\Temp\ipykernel_17588\1484115762.py:31: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  angle = torch.tensor(angle).float()


RuntimeError: Calculated padded input size per channel: (4 x 1). Kernel size: (2 x 2). Kernel size can't be greater than actual input size

In [90]:
Z_train.size()

torch.Size([800, 181])